// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc6VqanEUyr4zd6pXx6lwU87J82kxiL-k',
    appId: '1:863529359616:web:df6db654639da28b6fbbe5',
    messagingSenderId: '863529359616',
    projectId: 'laptopharbor-1b108',
    authDomain: 'laptopharbor-1b108.firebaseapp.com',
    databaseURL: 'https://laptopharbor-1b108-default-rtdb.firebaseio.com',
    storageBucket: 'laptopharbor-1b108.firebasestorage.app',
    measurementId: 'G-MSP9BS7GHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB60MIlPY6aQf7Yj7zmX0gc6YnjqRl_lgI',
    appId: '1:863529359616:android:e50315622b9df0386fbbe5',
    messagingSenderId: '863529359616',
    projectId: 'laptopharbor-1b108',
    databaseURL: 'https://laptopharbor-1b108-default-rtdb.firebaseio.com',
    storageBucket: 'laptopharbor-1b108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Mc5ki498YZ2lGWPcs9w9AJ99h7AV_oY',
    appId: '1:863529359616:ios:95609d2964c3bdc46fbbe5',
    messagingSenderId: '863529359616',
    projectId: 'laptopharbor-1b108',
    databaseURL: 'https://laptopharbor-1b108-default-rtdb.firebaseio.com',
    storageBucket: 'laptopharbor-1b108.firebasestorage.app',
    iosBundleId: 'com.example.laptopharbor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Mc5ki498YZ2lGWPcs9w9AJ99h7AV_oY',
    appId: '1:863529359616:ios:95609d2964c3bdc46fbbe5',
    messagingSenderId: '863529359616',
    projectId: 'laptopharbor-1b108',
    databaseURL: 'https://laptopharbor-1b108-default-rtdb.firebaseio.com',
    storageBucket: 'laptopharbor-1b108.firebasestorage.app',
    iosBundleId: 'com.example.laptopharbor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc6VqanEUyr4zd6pXx6lwU87J82kxiL-k',
    appId: '1:863529359616:web:bfb8362e9021076f6fbbe5',
    messagingSenderId: '863529359616',
    projectId: 'laptopharbor-1b108',
    authDomain: 'laptopharbor-1b108.firebaseapp.com',
    databaseURL: 'https://laptopharbor-1b108-default-rtdb.firebaseio.com',
    storageBucket: 'laptopharbor-1b108.firebasestorage.app',
    measurementId: 'G-MGQ5LPDXCT',
  );
}
